// Auto-generated by payload-domain-inspector
// Domain schema (compact view)

entity Product {
  id: ID
  title: string
  sku: string
  brand?: Brand
}

entity Stock {
  id: ID
  product: Product
  quantity: number
}
