import fs from "node:fs";
import path from "node:path";
import type { Entity, Field } from "../src/types";

function fieldToLine(field: Field): string {
  const type = field.isArray ? `${field.type}[]` : field.type;
  const optional = field.isOptional ? " (optional)" : "";
  const kind = field.kind === "relation" ? "relation" : "field";
  return `- \`${field.name}\`: ${type}${optional} — ${kind}`;
}

export function generateMarkdownSummary(entities: Entity[], outputDir: string) {
  const lines: string[] = [];

  lines.push("# Domain summary");
  lines.push("");
  lines.push("_Auto-generated by payload-domain-inspector_\n");

  for (const entity of entities) {
    lines.push(`## ${entity.name}`);
    lines.push("");
    lines.push("Поля:");
    lines.push("");
    for (const field of entity.fields) {
      lines.push(fieldToLine(field));
    }
    lines.push("");
  }

  const filePath = path.join(outputDir, "domain-summary.md");
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(filePath, lines.join("\n"), "utf-8");
}
