import fs from "node:fs";
import path from "node:path";
import type { Entity } from "../src/types";

export function generateDomainSchemaTs(entities: Entity[], outputDir: string) {
  const lines: string[] = [];

  lines.push("// Auto-generated by payload-domain-inspector");
  lines.push("// Domain schema (compact view)\n");

  for (const entity of entities) {
    lines.push(`entity ${entity.name} {`);
    for (const field of entity.fields) {
      const arraySuffix = field.isArray ? "[]" : "";
      const optionalSuffix = field.isOptional ? "?" : "";
      lines.push(
        `  ${field.name}${optionalSuffix}: ${field.type}${arraySuffix}`,
      );
    }
    lines.push("}\n");
  }

  const filePath = path.join(outputDir, "domain-schema.ts");
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(filePath, lines.join("\n"), "utf-8");
}
