import fs from "node:fs";
import path from "node:path";
import type { Entity } from "../src/types";

export function generateMermaidEr(entities: Entity[], outputDir: string) {
  const lines: string[] = [];

  lines.push("%% Auto-generated by payload-domain-inspector");
  lines.push("erDiagram");

  const relations: string[] = [];

  for (const entity of entities) {
    for (const field of entity.fields) {
      if (field.kind === "relation") {
        const from = entity.name;
        const to = field.type;
        const relationLine = `  ${from} ||--o{ ${to} : "${field.name}"`;
        relations.push(relationLine);
      }
    }
  }

  const uniqueRelations = [...new Set(relations)];
  lines.push(...uniqueRelations);

  const filePath = path.join(outputDir, "domain.er.mmd");
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(filePath, lines.join("\n"), "utf-8");
}
